name: demo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  #状态管理
  get: ^4.6.6
  #网络请求
  dio: ^5.4.0
  # 腾讯云 云开发
  cloudbase_flutter: ^1.0.3
  # 高德地图 flutter_line_sdk:
  amap_flutter_location: ^3.0.0
  amap_flutter_map: ^3.0.0

  #权限
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


